name: GitHub Actions Demo
on: [push]

jobs:
  TestModel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Download sa.engine release
        run: |
          curl -L -o "sa_engine_core_linux_x64.tar.gz" "https://studio.streamanalyze.com/download/Y2ktZGVtb0BzdHJlYW1hbmFseXplLmNvbQ==/3dae5506d45c299cb0b86a8e321d5f74/v4.16.2/linux/sa_engine_core_linux_x64.tar.gz"
      - name: install SA Engine
        run: |
          tar xzvf sa_engine_core_linux_x64.tar.gz
      - name: Test models
        run: |
          chmod +x ci/test-linux.sh && ci/test-linux.sh

  TestModelonEmulatedPi:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/streamanalyze/sa.qemu-pi:1.0.1
    steps:
      - name: Run entrypoint
        run: |
          screen -dm bash -c  "entrypoint.sh" & 
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: false
      - name: Test models
        run: |
          chmod +x ci/test-pi.sh && ci/test-pi.sh
